# klymo-ascent-1.0/data_loader.py

import os
from dataset import SatelliteSRDataset
from torch.utils.data import DataLoader

if __name__ == "__main__":
    # HR-first dataset: LR is generated by downsampling HR internally
    # so we only need hr_dir — no lr_dir
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    hr_dir = os.path.join(project_root, "worldstrat_processed", "HR_8bit")
    
    dataset = SatelliteSRDataset(
        hr_dir=hr_dir,
        lr_patch_size=128,
        scale=4
    )

    loader = DataLoader(
        dataset,
        batch_size=4,
        shuffle=True,
        num_workers=0  # 0 on Windows — num_workers>0 needs if __name__ guard in __main__ module
    )

    lr, hr = next(iter(loader))

    print("✅ Data pipeline check")
    print(f"LR shape: {lr.shape}")   # expect [4, 3, 128, 128]
    print(f"HR shape: {hr.shape}")   # expect [4, 3, 512, 512]
    print(f"LR range: {lr.min():.3f} → {lr.max():.3f}")  # expect 0.000 → 1.000
    print(f"HR range: {hr.min():.3f} → {hr.max():.3f}")  # expect 0.000 → 1.000